export const auth = {
    token: "Bearer BQAU7Ck4EiL_DrIwzuOC5FRxQHKtrTKgSdRDHvHmgq-xa6XgLYgX3hkOL-nCdWoUO3kobUJCIpT3wcBJMPbPok4excPa7DigUvS-Xt5c31rndMMwLEgC3cY7eRyWSL02pFuvTBDqMMlysTxU0HQZgoZTJRzVY9-fZ-ALp_jSm_rjGnOSX6ZQMhaCMSzhbHf54J4qFY0SLsJPkQAJA8TWgq4"
}